### ISSUE TITLE
Learning Materials Week 1 -- Anastasia

### ISSUE THREAD

**Issue by Ovaday** [Ovaday/planner-AI#68]
Hi Anastasia and welcome on the project.

As it is your first week and your request is more general, I will provide you with 2 parts - 1 to read some materials of what can you do to become a developer and grow professionally, and the second part is actually what you will, so practice skills. Additionally, I will make a practice task on the project for you and provide with that probably closer to Monday.

**1. Part one.**
- [x] https://www.freecodecamp.org/news/how-to-become-an-astounding-junior-developer/ -- Really good article, especially from "Own your growth—no one else will." chapter. Concepts described there can make a really valuable worker from you.
- [x] Try to use at least half of the concepts from the article above.

_Как систематизировать свои знания (Теория, читать через строчку):_ 
- [x] https://habr.com/ru/articles/695002/
- [x] https://vk.com/topic-55308304_30627163
- [x] https://qna.habr.com/q/281086

_Как систематизировать свои знания (практика):_ 
- [x] Create your own learning plan. It should include a list of all the technologies, programming languages, and frameworks you are familiar with. Write a brief description of each technology and a list of topics you have yet to master. This will help you see the big picture and understand what you need to learn next. **[Here you can use our roadmaps - roadmap.sh as a basis]**
- [x] Study related topics together. Web development encompasses many different technologies and programming languages. To learn effectively, try to study related topics together. For example, if you are studying HTML, you can study CSS at the same time.
- [x] Use online courses and instructional videos. There are many free and paid online courses in web development available on the internet. They can help you systematize your knowledge and fill in gaps in your knowledge base. Courses can include exercises, projects, and quizzes that can help you reinforce your knowledge.
- [x] Practice. The best way to learn web development is through practice. Create your own projects and solve problems on developer platforms. This will help you understand how technologies work in practice and give you the opportunity to apply your knowledge in practice.
- [x] Join the community. Join web developer communities and participate in discussions. This can help you exchange knowledge, get feedback, and find answers to your questions

**2. Part two.**
Введение:
Найти в гитхабе issue, Project и канбан-доску. Почитать:
- [x] https://asana.com/ru/resources/what-is-kanban
Знать для чего нужен каждый столбец в текущей канбан-доске. Перетащить свою Issue в нужный столбец (обновить статус). Посмотреть какие есть поля у задач и что такое Milestone в проекте.

Гит используется везде, тебе он нужен будет абсолютно всегда.
- [x] https://wiki.enchtex.info/howto/git -- база. Знать полностью. Тебе нужно понять и сделать следующую таску:
"Залогинься в проекте через PyCharm/WebStorm и добавь новую remote-ветку - данный репозиторий. Как только это будет готово сделай фетч и пулл. (_знать зачем_)
Сделай чекаут на ветке из этой задачи (_создать ветку от issue, если не понятно - спроси_), от нее создай новую ветку с рандомным названием и сделай коммит и пуш каких-то изменений в новую ветку.
Сделай черри пик данного коммита. (знать что такое черри пик)"
- [x] Знать что такое force push, как он влияет на коммиты и на ветку и почему его ни в коем случае нельзя использовать в коммерческой разработке. Уметь объяснить для чего нужен merge request и в чем отличие от пулл реквеста. Знать для чего нужен Amend local commits и что такое HEAD.
- [x] https://habr.com/ru/post/472600/ -- может пригодиться, подробное описание
- [x] https://gist.github.com/Jekins/2bf2d0638163f1294637 - полезно почитать что такое язык разметки, используется в Readme файлах, один из таких лежит в корне проекта

**[Практическое задание будет позже]**
